# Generated by Django 5.2.3 on 2025-10-16 10:34

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('emt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlcommunicationthread',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdl_thread', to='emt.eventproposal'),
        ),
        migrations.AddField(
            model_name='cdlmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_cdl_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cdlmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.cdlcommunicationthread'),
        ),
        migrations.AddField(
            model_name='cdlrequest',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdl_request', to='emt.eventproposal'),
        ),
        migrations.AddField(
            model_name='certificatebatch',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_batches', to='emt.eventproposal'),
        ),
        migrations.AddField(
            model_name='certificateentry',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.certificatebatch'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='emt.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultymeeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_faculty_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='impersonated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='original_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organization'),
        ),
        migrations.AddField(
            model_name='facultymeeting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_meetings', to='core.organization'),
        ),
        migrations.AddField(
            model_name='class',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.organization'),
        ),
        migrations.AddField(
            model_name='approvalflowtemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow_templates', to='core.organization'),
        ),
        migrations.AddField(
            model_name='approvalflowconfig',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow_config', to='core.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_types', to='core.organizationtype'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.organizationtype'),
        ),
        migrations.AddField(
            model_name='dashboardassignment',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizationtype'),
        ),
        migrations.AddField(
            model_name='popsoassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popsoassignment',
            name='assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popso_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popsoassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popso_assignments', to='core.organization'),
        ),
        migrations.AddField(
            model_name='popsochangenotification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='popsochangenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popso_notifications_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='core.program'),
        ),
        migrations.AddField(
            model_name='programspecificoutcome',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programspecificoutcome',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psos', to='core.program'),
        ),
        migrations.AddField(
            model_name='proofreadsubmission',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofread_submissions', to='emt.eventproposal'),
        ),
        migrations.AddField(
            model_name='proofreadsubmission',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofread_reviews_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proofreadsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofread_submissions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proofreaditem',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.proofreadsubmission'),
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='core.organization'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizationrole'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleeventapprovalvisibility',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_visibility', to='core.organizationrole'),
        ),
        migrations.AddField(
            model_name='sidebarmodule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.sidebarmodule'),
        ),
        migrations.AddField(
            model_name='sidebarpermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usereventapprovalvisibility',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizationrole'),
        ),
        migrations.AddField(
            model_name='usereventapprovalvisibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_box_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='approvalflowtemplate',
            unique_together={('organization', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'academic_year', 'role'], name='core_organi_organiz_62924f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization', 'academic_year')},
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='core_orgrole_name_ci_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationrole',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'org_type')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardassignment',
            unique_together={('user', 'role', 'dashboard')},
        ),
        migrations.AlterUniqueTogether(
            name='popsoassignment',
            unique_together={('organization', 'assigned_user')},
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['organization', 'academic_year', 'class_name'], name='core_ra_org_year_class_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('user', 'role'), name='unique_user_role_global'),
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('user', 'role', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='sidebarpermission',
            unique_together={('user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='usereventapprovalvisibility',
            unique_together={('user', 'role')},
        ),
    ]
