# Generated by Django 5.2.7 on 2025-11-01 15:48
from django.db import migrations

SDG_GOALS = [
    "No Poverty",
    "Zero Hunger",
    "Good Health and Well-Being",
    "Quality Education",
    "Gender Equality",
    "Clean Water and Sanitation",
    "Affordable and Clean Energy",
    "Decent Work and Economic Growth",
    "Industry, Innovation and Infrastructure",
    "Reduced Inequalities",
    "Sustainable Cities and Communities",
    "Responsible Consumption and Production",
    "Climate Action",
    "Life Below Water",
    "Life on Land",
    "Peace, Justice and Strong Institutions",
    "Partnerships for the Goals",
]


def seed_sdg_goals(apps, schema_editor):
    SDGGoal = apps.get_model("core", "SDGGoal")

    for idx, name in enumerate(SDG_GOALS, start=1):
        SDGGoal.objects.update_or_create(
            id=idx,
            defaults={"name": name},
        )

    SDGGoal.objects.filter(name__in=SDG_GOALS).exclude(
        id__in=range(1, len(SDG_GOALS) + 1)
    ).delete()

def unseed_sdg_goals(apps, schema_editor):
    SDGGoal = apps.get_model("core", "SDGGoal")
    SDGGoal.objects.filter(name__in=SDG_GOALS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(seed_sdg_goals, unseed_sdg_goals),
    ]
