# Generated by Django 5.2.3 on 2025-07-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_association_department_and_more"),
        ("emt", "0003_remove_eventproposal_association_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Association",
        ),
        migrations.DeleteModel(
            name="Cell",
        ),
        migrations.DeleteModel(
            name="Club",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
