# Generated by Django 5.2.3 on 2025-07-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_association_delete_cell_delete_club_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationtype',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
    ]
