# Generated by Django 5.2.3 on 2025-07-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_organizationtype_options_organization_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organizationtype'),
        ),
    ]
