# Generated by Django 5.2.3 on 2025-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_organizationtype_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtype",
            name="can_have_parent",
            field=models.BooleanField(default=False),
        ),
    ]
