# Generated by Django 5.2.3 on 2025-07-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organizationtype_can_have_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtype',
            name='parent',
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_types', to='core.organizationtype'),
        ),
    ]
