# Generated by Django 5.2.3 on 2025-07-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_organizationtype_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date_submitted',
            new_name='created_at',
        ),
    ]
