# Generated by Django 5.2.3 on 2025-07-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_approvalflowtemplate"),
        ("core", "0010_rename_date_submitted_report_created_at"),
    ]

    operations = []
