# Generated by Django 5.2.3 on 2025-07-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_is_active_to_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizationrole'),
        ),
    ]
