# Generated by Django 5.2.3 on 2025-07-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20250725_1530"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_faculty_incharge_first", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_flow_config",
                        to="core.organization",
                    ),
                ),
            ],
        ),
    ]
