# Generated by Django 5.2.3 on 2025-07-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_approvalflowconfig"),
        ("core", "0016_roleeventapprovalvisibility_and_more"),
    ]

    operations = []
