# Generated by Django 5.2.3 on 2025-07-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_organizationrole_description_and_more"),
        ("core", "0017_merge_20250730_0935"),
    ]

    operations = []
