# Generated by Django 5.2.3 on 2025-08-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalflowtemplate",
            name="optional",
            field=models.BooleanField(default=False),
        ),
    ]
