# Generated by Django 5.2.3 on 2025-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_roleassignment_organization_impersonationlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDGGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
