# Generated by Django 5.2.3 on 2025-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_organization_code_organization_meta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="register_no",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
