# Generated by Django 5.2.3 on 2025-08-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_profile_register_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="academic_year",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="core.organization",
            ),
        ),
    ]
