# Generated by Django 5.2.3 on 2025-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_roleassignment_academic_year_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
