# Generated by Django 5.2.3 on 2025-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_class_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
