# Generated by Django 5.2.3 on 2025-08-12 04:38

from django.db import migrations


def mark_inactive_and_set_activation(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("core", "Profile")
    # Mark users who never logged in as inactive
    User.objects.filter(last_login__isnull=True).update(is_active=False)
    # For active users, backfill activation time
    for user in User.objects.filter(is_active=True, last_login__isnull=False):
        Profile.objects.filter(user=user, activated_at__isnull=True).update(
            activated_at=user.last_login
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_profile_activated_at"),
    ]

    operations = [
        migrations.RunPython(mark_inactive_and_set_activation, migrations.RunPython.noop),
    ]
