# Generated by Django 5.2.3 on 2025-08-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_roleassignment_unique_user_role_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
