# Generated by Django 5.2.3 on 2025-08-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_facultymeeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="achievements_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="memberships_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
