# Generated by Django 5.2.3 on 2025-08-16 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_facultymeeting"),
        ("emt", "0021_cdlcertificaterecipient_cdlmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CDLCommunicationThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdl_thread",
                        to="emt.eventproposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CDLMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="cdl/messages/"),
                ),
                ("sent_via_email", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_cdl_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.cdlcommunicationthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CDLRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wants_cdl", models.BooleanField(default=False)),
                ("need_poster", models.BooleanField(default=False)),
                (
                    "poster_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("make", "Ask CDL to make the poster"),
                            ("correct", "Provide my own poster for correction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "poster_organization_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("poster_time", models.CharField(blank=True, max_length=100)),
                ("poster_date", models.CharField(blank=True, max_length=100)),
                ("poster_venue", models.CharField(blank=True, max_length=255)),
                (
                    "poster_resource_person",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "poster_resource_designation",
                    models.CharField(blank=True, max_length=255),
                ),
                ("poster_title", models.CharField(blank=True, max_length=255)),
                ("poster_summary", models.TextField(blank=True)),
                ("poster_design_link", models.URLField(blank=True)),
                ("poster_final_approved", models.BooleanField(default=False)),
                ("svc_photography", models.BooleanField(default=False)),
                ("svc_videography", models.BooleanField(default=False)),
                ("svc_digital_board", models.BooleanField(default=False)),
                ("svc_voluntary_cards", models.BooleanField(default=False)),
                ("need_certificate_any", models.BooleanField(default=False)),
                ("need_certificate_cdl", models.BooleanField(default=False)),
                (
                    "certificate_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("make", "Ask CDL to make the certificate"),
                            ("correct", "Provide my own certificate for correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("certificate_design_link", models.URLField(blank=True)),
                ("combined_design_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdl_request",
                        to="emt.eventproposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="cdl/certificates/")),
                (
                    "ai_check_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_batches",
                        to="emt.eventproposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CORE", "Core"),
                            ("HEAD", "Head"),
                            ("PARTICIPANT", "Participant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_role_text", models.CharField(blank=True, max_length=255)),
                ("ai_valid", models.BooleanField(default=False)),
                ("ai_errors", models.TextField(blank=True)),
                ("ready_for_cdl", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.certificatebatch",
                    ),
                ),
            ],
        ),
    ]
