# Generated by Django 5.2.3 on 2025-08-15 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_add_profile_fields_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Since the tables already exist, we'll use RunSQL to do nothing
        # but mark this migration as applied
        migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),  # Do nothing SQL
    ]
