# Generated by Django 5.2.3 on 2025-08-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_approvalflowtemplate_archived_at_and_more"),
        ("core", "0036_cdlcommunicationthread_cdlmessage_cdlrequest_and_more"),
        ("core", "0037_mark_existing_tables"),
    ]

    operations = []
