# Generated by Django 5.2.3 on 2025-08-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_sidebarpermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="achievements_visible",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bio_visible",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="memberships_visible",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_visible",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
    ]
