# Generated by Django 5.2.3 on 2025-08-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_sidebarpermission_add_org'),
        ('core', '0040_remove_profile_achievements_visible_and_more'),
    ]

    operations = [
    ]
