# Generated by Django 5.2.3 on 2025-09-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_cdlcommunicationmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="communication_date",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="report",
            name="communication_subject",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="report",
            name="generated_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="report",
            name="volunteer_rows",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
