# Generated by Django 5.2.3 on 2025-10-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sidebarmodule'),
        ('core', '0044_sidebarmodule'),
    ]

    operations = [
    ]
