# Generated by Django 5.2.3 on 2025-10-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_merge_0018_sidebarmodule_0044_sidebarmodule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sidebarmodule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
