# Generated by Django 5.2.3 on 2025-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_sidebarmodule_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdlrequest",
            name="certificate_design_link",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="combined_design_link",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_date",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_design_link",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_organization_name",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_resource_designation",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_resource_person",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_summary",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_time",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_title",
        ),
        migrations.RemoveField(
            model_name="cdlrequest",
            name="poster_venue",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="approvalflowtemplate",
            name="role_required",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cdlrequest",
            name="need_certificate_any",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="cdlrequest",
            name="need_poster",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="cdlrequest",
            name="poster_final_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="cdlrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="cdlrequest",
            name="wants_cdl",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="certificatebatch",
            name="ai_check_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="certificateentry",
            name="ai_valid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="certificateentry",
            name="ready_for_cdl",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="certificateentry",
            name="role",
            field=models.CharField(
                choices=[
                    ("CORE", "Core"),
                    ("HEAD", "Head"),
                    ("PARTICIPANT", "Participant"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="academic_year",
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="class",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="dashboardassignment",
            name="dashboard",
            field=models.CharField(
                choices=[
                    ("admin", "Admin Dashboard"),
                    ("faculty", "Faculty Dashboard"),
                    ("student", "Student Dashboard"),
                    ("cdl_head", "CDL Head Dashboard"),
                    ("cdl_work", "CDL Work Dashboard"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardassignment",
            name="role",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="facultymeeting",
            name="scheduled_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="impersonationlog",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="academic_year",
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("tutor", "Tutor"),
                ],
                db_index=True,
                default="student",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="organizationtype",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="popsoassignment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="popsochangenotification",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Created"),
                    ("UPDATE", "Updated"),
                    ("DELETE", "Deleted"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="popsochangenotification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="popsochangenotification",
            name="outcome_type",
            field=models.CharField(
                choices=[
                    ("PO", "Program Outcome"),
                    ("PSO", "Program Specific Outcome"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("hod", "HOD"),
                    ("admin", "Admin"),
                    ("club_convenor", "Club Convenor"),
                    ("event_coordinator", "Event Coordinator"),
                    ("committee_member", "Committee Member"),
                    ("iqac_member", "IQAC Member"),
                ],
                db_index=True,
                default="student",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="proofreaditem",
            name="kind",
            field=models.CharField(
                choices=[("file", "File"), ("text", "Text/Link")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proofreadsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("changes_needed", "Changes Needed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual"),
                    ("event", "Event"),
                    ("iqac", "IQAC"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sidebarmodule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="sidebarpermission",
            name="role",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
