# Generated by Django 5.2.3 on 2025-10-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_studentachievement_backfill'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS "core_activitylog_action_3e8b00da";
                DROP INDEX IF EXISTS "core_activitylog_action_3e8b00da_like";
                DROP INDEX IF EXISTS "core_activitylog_timestamp_4ee4ae7c";
                DROP INDEX IF EXISTS "core_approvalflowtemplate_role_required_05ff968f";
                DROP INDEX IF EXISTS "core_approvalflowtemplate_role_required_05ff968f_like";
                DROP INDEX IF EXISTS "core_cdlrequest_need_certificate_any_3b5b74a1";
                DROP INDEX IF EXISTS "core_cdlrequest_need_poster_71336c66";
                DROP INDEX IF EXISTS "core_cdlrequest_poster_final_approved_f6a37bac";
                DROP INDEX IF EXISTS "core_cdlrequest_updated_at_7b5d48c4";
                DROP INDEX IF EXISTS "core_cdlrequest_wants_cdl_859e112d";
                DROP INDEX IF EXISTS "core_certificatebatch_ai_check_status_f6b7590a";
                DROP INDEX IF EXISTS "core_certificatebatch_ai_check_status_f6b7590a_like";
                DROP INDEX IF EXISTS "core_certificateentry_ai_valid_3dca32c6";
                DROP INDEX IF EXISTS "core_certificateentry_ready_for_cdl_163413d6";
                DROP INDEX IF EXISTS "core_certificateentry_role_e7dea4ce";
                DROP INDEX IF EXISTS "core_certificateentry_role_e7dea4ce_like";
                DROP INDEX IF EXISTS "core_class_academic_year_d42c312a";
                DROP INDEX IF EXISTS "core_class_academic_year_d42c312a_like";
                DROP INDEX IF EXISTS "core_class_code_82b882ea";
                DROP INDEX IF EXISTS "core_class_code_82b882ea_like";
                DROP INDEX IF EXISTS "core_class_is_active_e2c53fb9";
                DROP INDEX IF EXISTS "core_dashboardassignment_dashboard_da4f8107";
                DROP INDEX IF EXISTS "core_dashboardassignment_dashboard_da4f8107_like";
                DROP INDEX IF EXISTS "core_dashboardassignment_role_44b43603";
                DROP INDEX IF EXISTS "core_dashboardassignment_role_44b43603_like";
                DROP INDEX IF EXISTS "core_facultymeeting_scheduled_at_3f88039d";
                DROP INDEX IF EXISTS "core_impersonationlog_started_at_34a09e0d";
                DROP INDEX IF EXISTS "core_organization_is_active_6c8bdc5e";
                DROP INDEX IF EXISTS "core_organizationmembership_academic_year_679e6587";
                DROP INDEX IF EXISTS "core_organizationmembership_academic_year_679e6587_like";
                DROP INDEX IF EXISTS "core_organizationmembership_is_active_fed0f51b";
                DROP INDEX IF EXISTS "core_organizationmembership_role_e471cf37";
                DROP INDEX IF EXISTS "core_organizationmembership_role_e471cf37_like";
                DROP INDEX IF EXISTS "core_organizationtype_is_active_8b95de26";
                DROP INDEX IF EXISTS "core_popsoassignment_is_active_d783464c";
                DROP INDEX IF EXISTS "core_popsochangenotification_action_4e58fb24";
                DROP INDEX IF EXISTS "core_popsochangenotification_action_4e58fb24_like";
                DROP INDEX IF EXISTS "core_popsochangenotification_is_read_094c7985";
                DROP INDEX IF EXISTS "core_popsochangenotification_outcome_type_3c2a77e7";
                DROP INDEX IF EXISTS "core_popsochangenotification_outcome_type_3c2a77e7_like";
                DROP INDEX IF EXISTS "core_profile_role_88508520";
                DROP INDEX IF EXISTS "core_profile_role_88508520_like";
                DROP INDEX IF EXISTS "core_proofreaditem_kind_4c8547e0";
                DROP INDEX IF EXISTS "core_proofreaditem_kind_4c8547e0_like";
                DROP INDEX IF EXISTS "core_proofreadsubmission_status_7ceed12c";
                DROP INDEX IF EXISTS "core_proofreadsubmission_status_7ceed12c_like";
                DROP INDEX IF EXISTS "core_report_created_at_02e053ba";
                DROP INDEX IF EXISTS "core_report_report_type_96f5d0d0";
                DROP INDEX IF EXISTS "core_report_report_type_96f5d0d0_like";
                DROP INDEX IF EXISTS "core_report_status_03593db0";
                DROP INDEX IF EXISTS "core_report_status_03593db0_like";
                DROP INDEX IF EXISTS "core_sidebarmodule_is_active_a33e62a1";
                DROP INDEX IF EXISTS "core_sidebarpermission_role_f55e9f7e";
                DROP INDEX IF EXISTS "core_sidebarpermission_role_f55e9f7e_like";
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='certificate_design_link',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='combined_design_link',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_date',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_design_link',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_organization_name',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_resource_designation',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_resource_person',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_summary',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_time',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_title',
        ),
        migrations.RemoveField(
            model_name='cdlrequest',
            name='poster_venue',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='approvalflowtemplate',
            name='role_required',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cdlrequest',
            name='need_certificate_any',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='cdlrequest',
            name='need_poster',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='cdlrequest',
            name='poster_final_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='cdlrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cdlrequest',
            name='wants_cdl',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='certificatebatch',
            name='ai_check_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificateentry',
            name='ai_valid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='certificateentry',
            name='ready_for_cdl',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='certificateentry',
            name='role',
            field=models.CharField(choices=[('CORE', 'Core'), ('HEAD', 'Head'), ('PARTICIPANT', 'Participant'), ('OTHER', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='dashboardassignment',
            name='dashboard',
            field=models.CharField(choices=[('admin', 'Admin Dashboard'), ('faculty', 'Faculty Dashboard'), ('student', 'Student Dashboard'), ('cdl_head', 'CDL Head Dashboard'), ('cdl_work', 'CDL Work Dashboard')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboardassignment',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='facultymeeting',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='academic_year',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('tutor', 'Tutor')], db_index=True, default='student', max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='popsoassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='popsochangenotification',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='popsochangenotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='popsochangenotification',
            name='outcome_type',
            field=models.CharField(choices=[('PO', 'Program Outcome'), ('PSO', 'Program Specific Outcome')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('hod', 'HOD'), ('admin', 'Admin'), ('club_convenor', 'Club Convenor'), ('event_coordinator', 'Event Coordinator'), ('committee_member', 'Committee Member'), ('iqac_member', 'IQAC Member')], db_index=True, default='student', max_length=32),
        ),
        migrations.AlterField(
            model_name='proofreaditem',
            name='kind',
            field=models.CharField(choices=[('file', 'File'), ('text', 'Text/Link')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='proofreadsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_needed', 'Changes Needed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('event', 'Event'), ('iqac', 'IQAC'), ('custom', 'Custom')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sidebarmodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sidebarmodule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sidebarpermission',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
