# Generated by Django 5.2.3 on 2025-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='ai_generated_report',
            field=models.TextField(blank=True, help_text='This field will store the report generated by AI.', null=True),
        ),
    ]
