# Generated by Django 5.2.3 on 2025-07-24 16:10

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('emt', '0003_remove_eventproposal_association_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalstep',
            options={
                'ordering': ['step_order'],
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
            },
        ),
        migrations.AlterModelOptions(
            name='eventproposal',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Event Proposal',
                'verbose_name_plural': 'Event Proposals',
            },
        ),
        migrations.AlterModelOptions(
            name='eventreport',
            options={
                'verbose_name': 'Event Report',
                'verbose_name_plural': 'Event Reports',
            },
        ),
        migrations.AlterModelOptions(
            name='expensedetail',
            options={
                'ordering': ['sl_no'],
                'verbose_name': 'Expense Detail',
                'verbose_name_plural': 'Expense Details',
            },
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='role_required',
            field=models.CharField(
                blank=True,
                choices=[
                    ('faculty', 'Faculty'),
                    ('dept_iqac', 'Department IQAC'),
                    ('hod', 'Head of Department'),
                    ('director', 'Director'),
                    ('dean', 'Dean'),
                    ('finance', 'Finance Officer'),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='eventexpectedoutcomes',
            name='proposal',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expected_outcomes',
                to='emt.eventproposal',
            ),
        ),
        migrations.AlterField(
            model_name='eventneedanalysis',
            name='proposal',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='need_analysis',
                to='emt.eventproposal',
            ),
        ),
        migrations.AlterField(
            model_name='eventobjectives',
            name='proposal',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='objectives',
                to='emt.eventproposal',
            ),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='committees',
            field=models.TextField(
                blank=True,
                help_text='List of committees involved.',
            ),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('submitted', 'Submitted'),
                    ('under_review', 'Under Review'),
                    ('waiting', 'Waiting for Action'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('returned', 'Returned for Revision'),
                    ('finalized', 'Finalized'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='student_coordinators',
            field=models.TextField(
                blank=True,
                help_text='Comma-separated student coordinator names (temporary).',
            ),
        ),
        migrations.AlterField(
            model_name='speakerprofile',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='speakers/',
            ),
        ),
        migrations.AlterField(
            model_name='speakerprofile',
            name='proposal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='speakers',
                to='emt.eventproposal',
            ),
        ),
        migrations.AlterField(
            model_name='tentativeflow',
            name='proposal',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tentative_flow',
                to='emt.eventproposal',
            ),
        ),
    ]
