# Generated by Django 5.2.3 on 2025-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emt', '0004_alter_approvalstep_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventproposal',
            name='student_coordinators',
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='student_coordinators',
            field=models.TextField(blank=True, help_text='Comma-separated student coordinator names (temporary).'),
        ),
    ]
