# Generated by Django 5.2.3 on 2025-07-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0005_remove_eventproposal_student_coordinators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="role_required",
            field=models.CharField(
                blank=True,
                choices=[
                    ("faculty", "Faculty"),
                    ("faculty_incharge", "Faculty In-Charge"),
                    ("dept_iqac", "Department IQAC"),
                    ("hod", "Head of Department"),
                    ("director", "Director"),
                    ("dean", "Dean"),
                    ("finance", "Finance Officer"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
