# Generated by Django 5.2.3 on 2025-07-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0006_alter_approvalstep_role_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="CDLSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("needs_support", models.BooleanField(default=False)),
                ("blog_content", models.TextField(blank=True)),
                ("poster_link", models.URLField(blank=True)),
                ("support_options", models.JSONField(blank=True, default=list)),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdl_support",
                        to="emt.eventproposal",
                    ),
                ),
            ],
        ),
    ]
