# Generated by Django 5.2.3 on 2025-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0008_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
