# Generated by Django 5.2.3 on 2025-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0008_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="event_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="event_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventproposal",
            name="pos_pso",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
