# Generated by Django 5.2.3 on 2025-08-08 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emt', '0011_eventproposal_aligned_sdg_goals_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproposal',
            name='report_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='report_assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to generate the report for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_report_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
