# Generated by Django 5.2.3 on 2025-08-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0012_eventproposal_report_assigned_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalstep",
            options={
                "ordering": ["order_index"],
                "verbose_name": "Approval Step",
                "verbose_name_plural": "Approval Steps",
            },
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="is_optional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="optional_unlocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
