# Generated by Django 5.2.3 on 2025-08-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_sdggoal"),
        ("emt", "0013_alter_approvalstep_options_approvalstep_decided_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="sdg_goals",
            field=models.ManyToManyField(
                blank=True, related_name="event_proposals", to="core.sdggoal"
            ),
        ),
        migrations.CreateModel(
            name="EventActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="emt.eventproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
    ]
