# Generated by Django 5.2.3 on 2025-08-09 18:19

from django.db import migrations


def copy_aligned_sdg_goals(apps, schema_editor):
    EventProposal = apps.get_model("emt", "EventProposal")
    SDGGoal = apps.get_model("core", "SDGGoal")
    for proposal in EventProposal.objects.all():
        text = getattr(proposal, "aligned_sdg_goals", "")
        if not text:
            continue
        names = [name.strip() for name in text.split(",") if name.strip()]
        for name in names:
            goal = SDGGoal.objects.filter(name__iexact=name).first()
            if goal:
                proposal.sdg_goals.add(goal)


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0014_eventproposal_sdg_goals_eventactivity"),
    ]

    operations = [
        migrations.RunPython(copy_aligned_sdg_goals, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="eventproposal",
            name="aligned_sdg_goals",
        ),
    ]
