# Generated by Django 5.2.3 on 2025-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0016_incomedetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="attendance_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
