# Generated by Django 5.2.3 on 2025-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0017_eventreport_attendance_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="actual_event_type",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
