# Generated by Django 5.2.3 on 2025-08-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0018_eventreport_actual_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="pos_pso",
            field=models.TextField(blank=True),
        ),
    ]
