# Generated by Django 5.2.3 on 2025-08-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0019_alter_eventproposal_pos_pso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdlsupport",
            name="poster_link",
        ),
        migrations.RemoveField(
            model_name="cdlsupport",
            name="support_options",
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="certificate_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cdl_create", "Ask CDL to make the certificate"),
                    ("provide_template", "Provide my own certificate template"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="certificate_design_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="certificate_help",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="certificates_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="other_services",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cdl_create", "Ask CDL to make the poster"),
                    ("provide_design", "Provide my own poster design"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_design_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_event_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_time",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="poster_venue",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="resource_person_designation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cdlsupport",
            name="resource_person_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
