# Generated by Django 5.2.3 on 2025-08-15 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0020_remove_cdlsupport_poster_link_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CDLCertificateRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("core_team", "Core Team Member"),
                            ("event_head", "Event Head / Coordinator"),
                            ("participant", "Participant"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ai_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "support",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_recipients",
                        to="emt.cdlsupport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CDLMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="cdl_messages/"),
                ),
                ("via_email", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="emt.cdlsupport",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
