# Generated by Django 5.2.3 on 2025-08-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0021_cdlcertificaterecipient_cdlmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_no", models.CharField(max_length=32)),
                ("full_name", models.CharField(max_length=128)),
                ("student_class", models.CharField(max_length=128)),
                ("absent", models.BooleanField(default=False)),
                ("volunteer", models.BooleanField(default=False)),
                (
                    "event_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_rows",
                        to="emt.eventreport",
                    ),
                ),
            ],
        ),
    ]
