# Generated by Django 5.2.3 on 2025-08-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0022_attendancerow"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="analysis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="organizing_committee",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="eventproposal",
            name="event_title",
            field=models.CharField(max_length=200),
        ),
    ]
