# Generated by Django 5.2.3 on 2025-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0023_eventreport_analysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="num_external_participants",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="num_faculty_participants",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="num_student_participants",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
