# Generated by Django 5.2.3 on 2025-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0024_eventreport_num_external_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="actual_speakers",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="challenges_analysis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="effectiveness_analysis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="impact_assessment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="key_achievements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="learning_outcomes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="lessons_learned",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="measurable_outcomes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="notable_moments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="objective_achievement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="participant_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="strengths_analysis",
            field=models.TextField(blank=True),
        ),
    ]
