# Generated by Django 5.2.3 on 2025-09-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0026_cdlassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerow",
            name="category",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("external", "External"),
                ],
                default="student",
                max_length=16,
            ),
        ),
    ]
