# Generated by Django 5.2.3 on 2025-09-06 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emt', '0026_cdlassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDLTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_key', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdl_resource_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdl_resource_tasks', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdl_task_assignments', to='emt.eventproposal')),
            ],
            options={
                'indexes': [models.Index(fields=['assignee'], name='emt_cdltask_assigne_9e354d_idx'), models.Index(fields=['proposal', 'resource_key'], name='emt_cdltask_proposa_e4388f_idx')],
                'unique_together': {('proposal', 'resource_key')},
            },
        ),
    ]
