# Generated by Copilot to merge branches and add CDLSupport completion fields
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    # Merge the two conflicting branches in emt app
    dependencies = [
        ('emt', '0027_attendancerow_category'),
        ('emt', '0028_cdltaskassignment_label_cdltaskassignment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cdlsupport',
            name='completed',
            field=models.BooleanField(default=False, help_text="When true, this event's CDL work is considered completed and shown under Analysis"),
        ),
        migrations.AddField(
            model_name='cdlsupport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdlsupport',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdl_completed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
