# Generated by Django 5.2.3 on 2025-09-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0029_merge_add_cdlsupport_completion"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE emt_eventreport
                        ADD COLUMN IF NOT EXISTS status VARCHAR(20);
                    """,
                    reverse_sql="""
                        ALTER TABLE emt_eventreport
                        DROP COLUMN IF EXISTS status;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE emt_eventreport
                        ALTER COLUMN status SET DEFAULT 'draft';
                    """,
                    reverse_sql="""
                        ALTER TABLE emt_eventreport
                        ALTER COLUMN status DROP DEFAULT;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        UPDATE emt_eventreport
                        SET status = COALESCE(NULLIF(status, ''), 'draft');
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE emt_eventreport
                        ALTER COLUMN status SET NOT NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE emt_eventreport
                        ALTER COLUMN status DROP NOT NULL;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="eventreport",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("finalized", "Finalized"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
        )
    ]
