# Generated by Django 5.2.3 on 2025-09-22 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_report_communication_date_and_more"),
        ("emt", "0029_merge_add_cdlsupport_completion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("photo", "Photograph"),
                            ("brochure", "Brochure Page"),
                            ("communication", "Communication (Letter/Email)"),
                            ("worksheet", "Worksheet / Activity"),
                            ("evaluation", "Evaluation Sheet"),
                            ("feedback", "Feedback Form"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="reports/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "pdf"],
                                message="Unsupported file type.",
                            )
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=300)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="core.report",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order_index", "id"],
            },
        ),
    ]
