# Generated by Django 5.2.3 on 2025-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0029_merge_add_cdlsupport_completion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventreportattachment",
            options={"ordering": ["category", "order_index", "id"]},
        ),
        migrations.AddField(
            model_name="eventreport",
            name="generated_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="eventreportattachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("photo", "Photographs"),
                    ("brochure", "Brochure Pages"),
                    ("communication", "Communication"),
                    ("worksheet", "Worksheets / Activities"),
                    ("evaluation", "Evaluation Sheet"),
                    ("feedback", "Feedback Form"),
                ],
                db_index=True,
                default="photo",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="eventreportattachment",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventreportattachment",
            name="requires_extraction",
            field=models.BooleanField(default=False),
        ),
    ]
