# Generated by Django 5.2.3 on 2025-09-23 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emt', '0029_merge_add_cdlsupport_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='review_stage',
            field=models.CharField(choices=[('user', 'With Submitter'), ('diqac', 'D-IQAC Coordinator'), ('hod', 'Head of Department'), ('uiqac', 'University IQAC Coordinator'), ('finalized', 'Finalized')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='session_feedback',
            field=models.TextField(blank=True, help_text='Latest review feedback for current session'),
        ),
        migrations.CreateModel(
            name='EventReportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='emt.eventreport')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
