# Generated by Django 5.2.3 on 2025-09-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0029_merge_add_cdlsupport_completion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventreportattachment",
            options={"ordering": ["order_index", "id"]},
        ),
        migrations.AddField(
            model_name="eventreportattachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("photo", "Photograph"),
                    ("brochure", "Brochure"),
                    ("communication", "Communication"),
                    ("worksheet", "Worksheet / Activity"),
                    ("evaluation", "Evaluation Sheet"),
                    ("feedback", "Feedback Form"),
                ],
                default="photo",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="eventreportattachment",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
