# Generated by Django 5.2.3 on 2025-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0032_remove_session_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="generated_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores the most recent autosave payload so partially completed reports can be recovered without breaking database constraints.",
            ),
        ),
    ]
