# Generated by Django 5.2.3 on 2025-10-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0034_merge_codex"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="is_user_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Hide draft from submitter while retaining it for admin review.",
            ),
        ),
    ]
