# Generated by GitHub Copilot on 2025-10-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt", "0034_merge_codex"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="current_semester",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
