# Generated by Django 5.2.3 on 2025-10-10 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_studentachievement_backfill'),
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ('-requested_on',), 'verbose_name': 'Membership Request', 'verbose_name_plural': 'Membership Requests'},
        ),
        migrations.RemoveConstraint(
            model_name='joinrequest',
            name='unique_pending_join_request',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='request_type',
            field=models.CharField(choices=[('join', 'Join'), ('leave', 'Leave')], default='join', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('user', 'organization', 'request_type'), name='unique_pending_join_request'),
        ),
    ]
