# Generated by Django 5.2.3 on 2025-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcript", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
